# PersistentVolumeClaim for RocksDB data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aggregator-sol-rocksdb-pvc
  namespace: aggregators
  labels:
    app: aggregator-sol
spec:
  accessModes:
    - ReadWriteOnce
  # Civo uses 'civo-volume' as the default storage class
  storageClassName: civo-volume
  resources:
    requests:
      storage: 10Gi
