apiVersion: v1
kind: ConfigMap
metadata:
  name: amm-eth-config
  namespace: aggregators
data:
  RUST_LOG: "info"
  ETH_PRICE_WS_PORT: "8080"
  ETH_API_PORT: "2222"
  UNISWAP_V4_SUBGRAPH_URL: "https://gateway.thegraph.com/api/8b89ea50ce2a4932ce038ea7e8cc9c36/subgraphs/id/DiYPVdygkfjDWhbxGSqAQxwBKmfKnkWQojqeM2rkLb3G"
