apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arbitrade-eth-pvc
  namespace: aggregators
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
