// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicAggreDealsV3Api {
    #[prost(message, repeated, tag = "1")]
    pub deals: ::prost::alloc::vec::Vec<PublicAggreDealsV3ApiItem>,
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicAggreDealsV3ApiItem {
    #[prost(string, tag = "1")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub quantity: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub trade_type: i32,
    #[prost(int64, tag = "4")]
    pub time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushDataV3ApiWrapper {
    #[prost(string, tag = "1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub symbol_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "5")]
    pub create_time: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "6")]
    pub send_time: ::core::option::Option<i64>,
    #[prost(oneof = "push_data_v3_api_wrapper::Body", tags = "314")]
    pub body: ::core::option::Option<push_data_v3_api_wrapper::Body>,
}
/// Nested message and enum types in `PushDataV3ApiWrapper`.
pub mod push_data_v3_api_wrapper {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "314")]
        PublicAggreDeals(super::PublicAggreDealsV3Api),
    }
}
